# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant
name: Editorial updates

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3
       - name: Set up JDK 1.8
         uses: actions/setup-java@v3
         with:
           distribution: 'zulu'
           java-version: '17'
       - name: Build with Ant
         run: ant -noinput -buildfile build.xml

       - name: Updating the edited texts in the repository
         run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add texts/workflow-output
          git commit -m "XML files are edited regarding editorial conventions"
          git push
